# Generated by Django 2.0.4 on 2018-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180422_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_pic',
            field=models.ImageField(default='images/default/empty-profile.png', upload_to='images/profiles/'),
        ),
    ]
