# Generated by Django 2.0.4 on 2018-04-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_profile_default_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_pic',
            field=models.ImageField(default='media/images/default/empty-profile.png', upload_to='media/images/profiles/'),
        ),
    ]
