# Generated by Django 2.0.4 on 2018-04-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.ImageField(default='images/default/cover-default.jpg', upload_to='images/blog_covers'),
        ),
    ]
